### ISSUE TITLE
Feature request: Add Iranian skins to OPUF ( OvGME)

### ISSUE THREAD

**Issue by 132ndNeck** [132nd-vWing/OPUF#3]
@132nd-Entropy Also, Can I ask for help to include the following skins into OvGME, so that I can use it in the OPUF campaign?

https://forums.eagle.ru/showthread.php?t=216906

It will make the realism a lot better once we start to work close to the Iranian assets which we will meet in the coming missions.

**Comment by 132ndNeck** [comment]
If yes, could you please check and verify that the skins is availeble for USAF aggressors (As I have that in backup on RED to make sure I can have all aircraft I need there )

**Comment by 132nd-Entropy** [comment]
hi, need help on this, maybe we can ask someone who wants to help out. I am happy to put the package into ovgme once its ready and the lua files edited for  USAF agressors etc

**Comment by thebgpikester** [comment]
I have a list. main issues to solve is the Iranian F-4 and F-14's may use other models (F-4 was a VSN one) and im not sure you wanna go there. But F-4 is too far away to get in game, so... up to you.
Mirage: is a challenge. may need custom skin. Else coalition tweaks
Viggen: Challenge skin template way large
F-4 no template, different model is available
F-14 same I believe.
C-130 is available
SU-24 is available
Awacs/IL-76 is available
There's a great UH-1 skin with Navy MH-60 markings that make it very good for carrier/naval
I have a great Sciud mod that I privatedly edited to make it fly much better. Scuds shoudl be in your modpack, but they may release soon.
Same issue with Arleiugh Burke... soon to be done by ED but when...
Spruance is available (time period right)

**Comment by thebgpikester** [comment]
OK I've got this done. Best news is... all in saved games so it's not affecting game files.
Will begin with just required skins you really need. can talk about fringe stuff later. will upload to here asap.

**Comment by thebgpikester** [comment]
OK done. Download from  here: https://drive.google.com/file/d/1yeBlSAyZtJHT3Jm5_Pf7cyO0RSBsD-TY/view?usp=sharing
*****************************
IRIAF skins and an SH-60 skin on the high quality UH-60 (for Stennis deck purposes) - collector Pikey
IL-76 AWACS (KJ-2000)
https://www.digitalcombatsimulator.com/en/files/3301384/

C-130(1) https://www.digitalcombatsimulator.com/en/files/3301388/

KC-130 https://www.digitalcombatsimulator.com/en/files/3301390/

F-4E https://www.digitalcombatsimulator.com/en/files/3301808/

F-14A https://www.digitalcombatsimulator.com/en/files/3301691/

IL-76 https://www.digitalcombatsimulator.com/en/files/3301385/

UH-60 https://www.digitalcombatsimulator.com/en/files/3300884/

I could NOT find a satisfactory Mirage skin. I didn't look for anything else. I tested the Su24 skin and it didn't work so I excluded it.
The UH60 skin is an odd one, the reason is, the low quality in game SH60 is garbage on a carrier deck. However, if you paint it blue like a SH-60 no one will tell the difference. You can use these for plane guards and deck statics.

**Comment by 132nd-Entropy** [comment]
thanks a ton for your help, also thanks Bilgatus for helping with the remaining skins. added them to ovgme for Iran upload pending
